### ISSUE TITLE
No way to disable WebSocket errors from being logged

### ISSUE THREAD

**Issue by tugando** [jjxxs/websocket-ts#12]
There is no way to disable web socket error messages from being logged.  It would be great if the tool provided a global Boolean settings which would allow one to prevent these errors from logging.

![Capture](https://user-images.githubusercontent.com/6185544/110964717-7846d700-8321-11eb-981f-c530c689235b.JPG)

**Comment by jjxxs** [comment]
Hi! These log-messages are not issued by this library but rather the browsers (native) websocket-functionality. In fact, _this library does not print any messages at all_. As far as I know it's not possible to suppress these. Read more about it here: https://stackoverflow.com/a/31003057/3762311

Feel free to re-open this issue, if you have other information on this.
