### ISSUE TITLE
Feature Request: Allow customizing protocol before automatic reconnect `withBackoff`

### ISSUE THREAD

**Issue by HarshRohila** [jjxxs/websocket-ts#17]
Use case: Websocket protocol value is used for sending auth token, which expires after some time. A new token needs to be fetched and set(in the protocol) before reconnecting
The new protocol value will be fetched (returning a promise), so reconnect should be able to wait for the promise to get fulfilled

**Comment by HarshRohila** [comment]
The API can look like this
```typescript
withAutoReconnect(options: AutoReconnectOptions)

interface AutoReconnectOptions {
    getProtocols: () => Promise<string | string[]>
    backoff: Backoff
}
```

**Comment by HarshRohila** [comment]
Looking at code, found easy way of doing this, allowing protocol value to be a function returning promise
Created PR for that https://github.com/jjxxs/websocket-ts/pull/18

**Comment by jjxxs** [comment]
I like the idea, I might come back to this but will close the issue and the appending PR for now.
