### ISSUE TITLE
Explicit close should clear retry timeout

### ISSUE THREAD

**Issue by steveluscher** [jjxxs/websocket-ts#22]
Based on a quick read of this source code:

https://github.com/jjxxs/websocket-ts/blob/0b9673c1799293d08d9de9d0d71c6711c628412b/src/websocket.ts#L150-L160

And this:

https://github.com/jjxxs/websocket-ts/blob/0b9673c1799293d08d9de9d0d71c6711c628412b/src/websocket.ts#L71-L74

I believe it to be the case that:

* if you have a pending reconnect timeout, then
* you call `close()`

…the reconnect timeout won't be cancelled, and the websocket will try to reconnect. I believe this shouldn't happen after an explicit call to `close()`.

**Comment by jjxxs** [comment]
you are correct. i will include this in the upcoming release and leave this issue open until then. thanks for the report!

**Comment by jjxxs** [comment]
Fixed in latest release https://github.com/jjxxs/websocket-ts/releases/tag/v2.1.4

Closing this issue, thanks for the report @steveluscher
