### ISSUE TITLE
Export backoff classes

### ISSUE THREAD

**Issue by UnwrittenFun** [jjxxs/websocket-ts#9]
The various backoff implementations aren't available to be imported from the root of the package, meaning I would have to import them from something like `websocket-ts/lib/backoff/exponentialbackoff`. 

Would be great if these could be exported by the root index.ts

**Comment by jjxxs** [comment]
Thanks for bringing this up. The backoff- and buffer-implementations will be exported in the next release.

**Comment by jjxxs** [comment]
Fixed in newest release v1.1.0.
